### ISSUE TITLE
[1.18.2] Can't connect to server

### ISSUE THREAD

**Issue by gilyerm** [McJty/TheOneProbe#573]
I'm running a mohist-1.18.2 server (v.85 - Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.68) on java 17
I created a private modpack and I got this problem when I tried to connect to my server:
```
[ERROR]: Exception caught during firing event: Cannot invoke "com.mojang.authlib.GameProfile.getName()" because "this.f_36084_" is null
        Index: 14
        Listeners
        ...
        14: ASM: mcjty.theoneprobe.ForgeEventHandlers@6702e427 onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
        ...
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getName()" because "this.f_36084_" is null
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_7755_(Player.java:1820)
        at TRANSFORMER/forge@40.1.68/org.bukkit.craftbukkit.v1_18_R2.entity.CraftLivingEntity.<init>(CraftLivingEntity.java:81)
        at TRANSFORMER/forge@40.1.68/org.bukkit.craftbukkit.v1_18_R2.entity.CraftHumanEntity.<init>(CraftHumanEntity.java:70)
        at TRANSFORMER/forge@40.1.68/org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.<init>(CraftPlayer.java:118)
        at TRANSFORMER/forge@40.1.68/org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.getEntity(CraftEntity.java:98)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Entity.getBukkitEntity(Entity.java:275)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.getBukkitEntity(Player.java:181)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.getBukkitEntity(ServerPlayer.java:268)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_21223_(LivingEntity.java:1134)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_6084_(LivingEntity.java:1649)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.getCapability(Player.java:2220)
        at TRANSFORMER/forge@40.1.68/net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:34)
        at TRANSFORMER/theoneprobe@1.18-5.1.0/mcjty.theoneprobe.ForgeEventHandlers.onEntityConstructing(ForgeEventHandlers.java:37)
        at net.minecraftforge.eventbus.ASMEventHandler_480_ForgeEventHandlers_onEntityConstructing_AttachCapabilitiesEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.1.68/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:593)
        at TRANSFORMER/forge@40.1.68/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:587)
        at TRANSFORMER/forge@40.1.68/net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:73)
        at TRANSFORMER/forge@40.1.68/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:68)
        at TRANSFORMER/forge@40.1.68/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:52)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Entity.<init>(Entity.java:319)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:250)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.<init>(Player.java:186)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:272)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:457)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:75)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:241)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:153)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1055)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:376)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:963)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:786)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:286)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
when I remove the mod from my server I can connect to the server without any problem

**Comment by McJty** [comment]
You have the mod on the client as well?

Op za 23 jul. 2022 11:51 schreef Gilyerm ***@***.***>:

**Comment by gilyerm** [comment]
yes i have

**Comment by McJty** [comment]
Weird. Never seen this before and the one probe is used a lot of servers.
So at this moment I have no idea

Op za 23 jul. 2022 12:36 schreef Gilyerm ***@***.***>:

**Comment by gilyerm** [comment]
if you want I can give you the list of mods in the client and in the server to troubleshoot that

**Comment by McJty** [comment]
Yes that would be nice


Op za 23 jul. 2022 12:39 schreef Gilyerm ***@***.***>:

**Comment by gilyerm** [comment]
```yaml
#client
forge version: 40.1.68
client mods:
- AkashicTome-1.5-20.jar
- angelring-1.18.2-2.0.2.jar
- Apotheosis-1.18.2-5.3.6.jar
- appleskin-forge-mc1.18-2.4.0.jar
- architectury-4.6.77-forge.jar
- AutoRegLib-1.7-53.jar
- badpackets-forge-0.1.2.jar
- balm-3.1.0+0.jar
- BetterF3-1.2.5-Forge-1.18.2.jar
- Bookshelf-Forge-1.18.2-13.2.21.jar
- caelus-forge-1.18.1-3.0.0.2.jar
- charginggadgets-1.7.0.jar
- ChiselsBits-forge-1.18.2-1.2.113-universal.jar
- cloth-config-6.2.62-forge.jar
- Clumps-forge-1.18.2-8.0.0+13.jar
- cobblegenrandomizer-1.18.2-1.0.0.jar
- cofh_core-1.18.2-1.6.4.21.jar
- configured-1.5.3-1.18.2.jar
- Controlling-forge-1.18.2-9.0+21.jar
- Create-Curios-1.18.2-v1.0.0.jar
- create-mc1.18.2_v0.5.0c.jar
- createaddition-1.18.2-20220715a.jar
- curioofundying-forge-1.18-5.3.0.0.jar
- curios-forge-1.18.2-5.0.7.1.jar
- curiouselytra-forge-1.18.1-5.0.1.0.jar
- dpanvil-1.18.2-3.4.1.jar
- easy_piglins-1.18.2-1.0.0.jar
- easy_villagers-1.18.2-1.0.11.jar
- EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar
- enderchests-1.18-1.9.6.jar
- endertanks-1.18-1.11.7.jar
- extremesoundmuffler-3.28_forge-1.18.2.jar
- FarmersDelight-1.18.2-1.1.2.jar
- FastFurnace-1.18.2-6.0.3.jar
- FastWorkbench-1.18.2-6.0.2.jar
- feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
- flatbedrock-1.4.2-build.10+mc1.18.2.jar
- flywheel-forge-1.18-0.6.4.jar
- ftb-chunks-forge-1802.3.6-build.147.jar
- ftb-essentials-1802.1.7-build.42.jar
- ftb-industrial-contraptions-1802.1.6-build.197.jar
- ftb-library-forge-1802.3.6-build.123.jar
- ftb-teams-forge-1802.2.6-build.51.jar
- ftb-ultimine-forge-1802.3.3-build.55.jar
- functionalstorage-1.18.2-0.0.19.jar
- inventorysorter-1.18-19.0.0.jar
- ironchest-1.18.2-13.1.9.jar
- itemcollectors-1.1.5-mc1.18.jar
- JAMD-1.7.0-build.25+mc1.18.2.jar
- JAVD-3.0.0-build.54+mc1.18.2.jar
- jei-1.18.2-9.7.0.209.jar
- JustEnoughResources-1.18.2-0.14.1.171.jar
- kubejs-create-forge-1802.2.2-build.26.jar
- kubejs-forge-1802.5.4-build.524.jar
- kubejs-thermal-1802.1.5-build.14.jar
- laserio-1.3.3.jar
- light-overlay-6.0.5-forge.jar
- lootr-1.18.2-0.2.19.56.jar
- modnametooltip-1.18.1-1.18.0.jar
- MouseTweaks-forge-mc1.18-2.21.jar
- myrtrees-forge-1.1.0-build.29.jar
- netherportalfix-forge-1.18-9.0.0.jar
- Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2.jar
- Patchouli-1.18.2-71.1.jar
- Placebo-1.18.2-6.4.2.jar
- refinedstorage-1.10.2.jar
- refinedstorageaddons-0.8.2.jar
- repurposed_structures_forge-5.1.14+1.18.2.jar
- rhino-forge-1802.1.14-build.206.jar
- rsrequestify-2.2.0.jar
- selene-1.18.2-1.17.9.jar
- shetiphiancore-1.18-3.10.10.jar
- shutupexperimentalsettings-1.0.5.jar
- sophisticatedbackpacks-1.18.2-3.18.4.646.jar
- sophisticatedcore-1.18.2-0.4.5.76.jar
- spark-1.9.11-forge.jar
- structure_gel-1.18.2-2.4.6.jar
- SuperCircuitMaker2-0.2.9+1.18.2.jar
- supermartijn642configlib-1.1.6-forge-mc1.18.jar
- supermartijn642corelib-1.0.19-forge-mc1.18.jar
- supplementaries-1.18.2-1.4.8.jar
- TerraBlender-forge-1.18.2-1.1.0.102.jar
- theoneprobe-1.18-5.1.0.jar
- thermal_expansion-1.18.2-1.6.3.13.jar
- thermal_foundation-1.18.2-1.6.3.28.jar
- thermal_innovation-1.18.2-1.6.3.12.jar
- titanium-1.18.2-3.5.6-38.jar
- TKLib-0.0.23+1.18.2.jar
- ToastControl-1.18.2-6.0.2.jar
- torchmaster-18.1.0.jar
- trade-cycling-forge-1.18.2-1.0.2.jar
- trashcans-1.0.15-forge-mc1.18.jar
- twilightforest-1.18.2-4.1.1184-universal.jar

# server
server version: mohist-1.18.2-85-server
server plugins: none
server mods:
- AkashicTome-1.5-20.jar
- angelring-1.18.2-2.0.2.jar
- Apotheosis-1.18.2-5.3.6.jar
- architectury-4.6.77-forge.jar
- AutoRegLib-1.7-53.jar
- badpackets-forge-0.1.2.jar
- balm-3.1.0+0.jar
- Bookshelf-Forge-1.18.2-13.2.21.jar
- caelus-forge-1.18.1-3.0.0.2.jar
- charginggadgets-1.7.0.jar
- ChiselsBits-forge-1.18.2-1.2.113-universal.jar
- cloth-config-6.2.62-forge.jar
- Clumps-forge-1.18.2-8.0.0+13.jar
- cobblegenrandomizer-1.18.2-1.0.0.jar
- cofh_core-1.18.2-1.6.4.21.jar
- configured-1.5.3-1.18.2.jar
- Create-Curios-1.18.2-v1.0.0.jar
- create-mc1.18.2_v0.5.0c.jar
- createaddition-1.18.2-20220715a.jar
- curioofundying-forge-1.18-5.3.0.0.jar
- curios-forge-1.18.2-5.0.7.1.jar
- curiouselytra-forge-1.18.1-5.0.1.0.jar
- dpanvil-1.18.2-3.4.1.jar
- easy_piglins-1.18.2-1.0.0.jar
- easy_villagers-1.18.2-1.0.11.jar
- EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar
- enderchests-1.18-1.9.6.jar
- endertanks-1.18-1.11.7.jar
- extremesoundmuffler-3.28_forge-1.18.2.jar
- FarmersDelight-1.18.2-1.1.2.jar
- FastFurnace-1.18.2-6.0.3.jar
- FastWorkbench-1.18.2-6.0.2.jar
- feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
- flatbedrock-1.4.2-build.10+mc1.18.2.jar
- flywheel-forge-1.18-0.6.4.jar
- ftb-chunks-forge-1802.3.6-build.147.jar
- ftb-essentials-1802.1.7-build.42.jar
- ftb-industrial-contraptions-1802.1.6-build.197.jar
- ftb-library-forge-1802.3.6-build.123.jar
- ftb-teams-forge-1802.2.6-build.51.jar
- ftb-ultimine-forge-1802.3.3-build.55.jar
- functionalstorage-1.18.2-0.0.19.jar
- inventorysorter-1.18-19.0.0.jar
- ironchest-1.18.2-13.1.9.jar
- itemcollectors-1.1.5-mc1.18.jar
- JAMD-1.7.0-build.25+mc1.18.2.jar
- JAVD-3.0.0-build.54+mc1.18.2.jar
- jei-1.18.2-9.7.0.209.jar
- JustEnoughResources-1.18.2-0.14.1.171.jar
- kubejs-create-forge-1802.2.2-build.26.jar
- kubejs-forge-1802.5.4-build.524.jar
- kubejs-thermal-1802.1.5-build.14.jar
- laserio-1.3.3.jar
- light-overlay-6.0.5-forge.jar
- lootr-1.18.2-0.2.19.56.jar
- myrtrees-forge-1.1.0-build.29.jar
- netherportalfix-forge-1.18-9.0.0.jar
- Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2.jar
- Patchouli-1.18.2-71.1.jar
- Placebo-1.18.2-6.4.2.jar
- refinedstorage-1.10.2.jar
- refinedstorageaddons-0.8.2.jar
- repurposed_structures_forge-5.1.14+1.18.2.jar
- rhino-forge-1802.1.14-build.206.jar
- rsrequestify-2.2.0.jar
- selene-1.18.2-1.17.9.jar
- shetiphiancore-1.18-3.10.10.jar
- sophisticatedbackpacks-1.18.2-3.18.4.646.jar
- sophisticatedcore-1.18.2-0.4.5.76.jar
- spark-1.9.11-forge.jar
- structure_gel-1.18.2-2.4.6.jar
- SuperCircuitMaker2-0.2.9+1.18.2.jar
- supermartijn642configlib-1.1.6-forge-mc1.18.jar
- supermartijn642corelib-1.0.19-forge-mc1.18.jar
- supplementaries-1.18.2-1.4.8.jar
- TerraBlender-forge-1.18.2-1.1.0.102.jar
- theoneprobe-1.18-5.1.0.jar
- thermal_expansion-1.18.2-1.6.3.13.jar
- thermal_foundation-1.18.2-1.6.3.28.jar
- thermal_innovation-1.18.2-1.6.3.12.jar
- titanium-1.18.2-3.5.6-38.jar
- TKLib-0.0.23+1.18.2.jar
- torchmaster-18.1.0.jar
- trade-cycling-forge-1.18.2-1.0.2.jar
- trashcans-1.0.15-forge-mc1.18.jar
- twilightforest-1.18.2-4.1.1184-universal.jar
```
